default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sportrender_development
  pool: 1000

test:
  <<: *default
  database: sr_test

production:
  <<: *default
  database: sr_production
  username: sr
  password: <%= ENV['SR_DATABASE_PASSWORD'] %>
